guru/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :pujas
  get 'lineages/index'
  root 'lineages#index'

  resources :pictures
  get 'lineages/index'
  root 'lineages#index'

end

guru/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, :all
       else
         can :read, :all
       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

guru/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

guru/app/models/article.rb
class Article < ApplicationRecord
end

guru/app/models/picture.rb
class Picture < ApplicationRecord
    mount_uploader :picture_image, PictureImageUploader
    belongs_to :user
end

guru/app/models/puja.rb
class Puja < ApplicationRecord
  belongs_to :user
end

guru/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :trackable, :validatable,
       :omniauthable, :omniauth_providers => [:facebook]
  has_many :pujas
  has_many :pictures

  def self.from_omniauth(auth)
      # Case 1: Find existing user by facebook uid
      user = User.find_by_fb_uid( auth.uid )
      if user
         user.fb_token = auth.credentials.token
         #user.fb_raw_data = auth
         user.save!
         return user
      end

      # Case 2: Find existing user by email
      existing_user = User.find_by_email( auth.info.email )
      if existing_user
        existing_user.fb_uid = auth.uid
        existing_user.fb_token = auth.credentials.token
        #existing_user.fb_raw_data = auth
        existing_user.save!
        return existing_user
      end

      # Case 3: Create new password
      user = User.new
      user.fb_uid = auth.uid
      user.fb_token = auth.credentials.token
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      #user.fb_raw_data = auth
      user.save!
      return user
    end
end

guru/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
end

guru/app/controllers/lineages_controller.rb
class LineagesController < ApplicationController
  def index
  end
end

guru/app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
   @pictures = Picture.all.paginate(page: params[:page], per_page: 6).order("created_at DESC")
 end

  def show
     @picture = Picture.find(params[:id])
   end

  def new
    @picture = current_user.pictures.build
    authorize! :create, @picture
  end

  def edit
    @picture = Picture.find(params[:id])
    authorize! :update, @picture
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    authorize! :create, @picture
    @picture.save
    redirect_to @picture
  end

  def update
    @picture = Picture.find(params[:id])
    authorize! :update, @picture
    if @picture.update(picture_params)
      redirect_to @picture
    else
      render 'edit'
    end
  end


  def destroy
    @picture = Picture.find(params[:id])
    authorize! :destroy, @picture
    @picture.destroy

    redirect_to pictures_path
  end


  private
    def picture_params
      params.require(:picture).permit(:title, :description, :picture_image)
    end

end

guru/app/controllers/pujas_controller.rb
class PujasController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]


    def index
     @pujas = Puja.all.paginate(page: params[:page], per_page: 6).order("created_at DESC")
    end

    def show
      @puja = Puja.find(params[:id])
    end

    def new
      @puja = current_user.pujas.build
      authorize! :create, @puja
    end

    def edit
      @puja = Puja.find(params[:id])
      authorize! :update, @puja
    end

    def create
      @puja = current_user.pujas.build(puja_params)
      authorize! :create, @puja

      @puja.save
      redirect_to @puja
    end

    def update
      @puja = Puja.find(params[:id])
      authorize! :update, @puja
      if @puja.update(puja_params)
        redirect_to @puja
      else
        render 'edit'
      end
    end

    def destroy
      @puja = Puja.find(params[:id])
      authorize! :destroy, @puja
      @puja.destroy

      redirect_to pujas_path
    end



  private
  def puja_params
    params.require(:puja).permit(:name, :description, :benefit, :suggested_offering)
  end

end

guru/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

end

guru/app/helpers/application_helper.rb
module ApplicationHelper
end

guru/app/helpers/lineages_helper.rb
module LineagesHelper
end

guru/app/helpers/pictures_helper.rb
module PicturesHelper
end

guru/app/helpers/pujas_helper.rb
module PujasHelper
end

guru/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Guru</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      <%= link_to('Log Out', destroy_user_session_path, :method => :delete) %>
    <% else %>
      <%= link_to "Facebook Log In", user_facebook_omniauth_authorize_path %>
    <% end %>
     
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
    <%= yield %>
  </body>
</html>

guru/app/views/lineages/index.html.erb
<h1>Welcome to guru homepage</h1>
<p>about guru. our guru is</p>



<%= link_to 'Available Pujas', controller: 'pujas' %>

<%= link_to 'Add New pictures', controller: 'pictures' %>
<!-- would be an admin only function -->

<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>
  </li>
<% end %>

<% if user_signed_in? %>
  <li>
  <%= link_to('Edit registration', edit_user_registration_path) %>
  </li>
<% else %>
  <li>
  <%= link_to('Register', new_user_registration_path)  %>
  </li>
<% end %>

guru/app/views/pictures/edit.html.erb
<h1>Edit picture here</h1>



<%= form_for :picture, url: pictures_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :picture_image %>
    <%= f.file_field :picture_image %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', pictures_path %>

guru/app/views/pictures/index.html.erb
<h1> listing of pujas pictures </h1>

<% @pictures.each do |picture| %>


    <p>Tile: <%= picture.title %> </p>
    <%= image_tag picture.picture_image.thumb.url %>
    <p>Description:<br> <%= picture.description.truncate_words(25) %> </p>

    <%= link_to 'Click on more details to see picture', picture_path(picture) %> <br>
    <% if can? :update, @picture %>
      <%= link_to 'Edit', edit_picture_path(picture) %>
    <% end %>
    <% if can? :destroy, @picture %>
      <%= link_to 'Destroy', picture_path(picture),
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
    <% end %>
     <br>

<% end %>

<% if can? :create, @picture %>
  <%= link_to 'New picture', new_picture_path %>
<% end %>

<%= link_to 'Home Page', root_path %>

<div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @pictures %>
    </div>
    <%= will_paginate @pictures, :container => false %>
  </div>

guru/app/views/pictures/new.html.erb
<h1>Post a new picture here</h1>



<%= form_for :picture, url: pictures_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :picture_image %>
    <%= f.file_field :picture_image %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', pictures_path %>

guru/app/views/pictures/show.html.erb
<h1> Picture </h1>

<p>
  <strong>Title:</strong>
  <%= @picture.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @picture.description %>
</p>

<p>
  <%= image_tag @picture.picture_image.url %>
</p>

<%= link_to 'Back', pictures_path %>

guru/app/views/pujas/edit.html.erb
<h1>Edit puja here</h1>



<%= form_for :puja, url: pujas_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :benefit %><br>
    <%= f.text_area :benefit %>
  </p>

  <p>
    <%= f.label :suggested_offering %><br>
    <%= f.text_field :suggested_offering %>
  </p>


  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', pujas_path %>

guru/app/views/pujas/index.html.erb
<h1> listing of pujas available </h1>

<% @pujas.each do |puja| %>

    <p>Name: <%= puja.name %> </p>
    <p>Description:<br> <%= puja.description.truncate_words(25) %> </p>
    <p>Benefit:<br> <%= puja.benefit.truncate_words(25) %> </p>
    <p>Suggested_offering: <%= puja.suggested_offering %> </p>
    <%= link_to 'More Details', puja_path(puja) %> <br>
    <% if can? :update, @puja %>
      <%= link_to 'Edit', edit_puja_path(puja) %>
    <% end %>
    <% if can? :destroy, @puja %>
      <%= link_to 'Destroy', puja_path(puja),
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
    <% end %>
     <br>

<% end %>


<% if can? :create, @puja %>
  <%= link_to 'New puja', new_puja_path %>
<% end %>
<%= link_to 'Home Page', root_path %>
<!-- note that this link would be lock in the future so that only admin can access -->
<br><br>
<div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @pujas %>
    </div>
    <%= will_paginate @pujas, :container => false %>
  </div>

guru/app/views/pujas/new.html.erb
<h1>Post a new puja here</h1>



<%= form_for :puja, url: pujas_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :benefit %><br>
    <%= f.text_area :benefit %>
  </p>

  <p>
    <%= f.label :suggested_offering %><br>
    <%= f.text_field :suggested_offering %>
  </p>


  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', pujas_path %>

guru/app/views/pujas/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @puja.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @puja.description %>
</p>

<p>
  <strong>Benefit:</strong>
  <%= @puja.benefit %>
</p>

<p>
  <strong>Suggested_offering:</strong>
  <%= @puja.suggested_offering %>
</p>

<%= link_to 'Back', pujas_path %>